import { requireSupabase, isSupabaseConfigured } from '../config/supabase.js';
import { renderShell } from '../components/shell.js';
import { emailIsValid } from '../utils/validation.js';
import { showToast } from '../utils/toast.js';
import { setDocumentMeta } from '../utils/helpers.js';

function configMessage() { return !isSupabaseConfigured ? `<div class="alert alert-warning d-flex gap-2 small" role="alert"><i class="bi bi-info-circle-fill"></i><span>Add the two Supabase values to <code>.env.local</code> to enable account actions.</span></div>` : ''; }
function submitButton(label) { return `<button class="btn btn-primary w-100" type="submit"><span>${label}</span><span class="spinner-border spinner-border-sm d-none" aria-hidden="true"></span></button>`; }
function authLayout(title, subtitle, form, footer) { return `<section class="auth-wrap"><div class="auth-card"><a data-route href="/" class="brand d-inline-block mb-4"><span class="brand-mark">♥</span>Dearly</a><h1 class="h2 mb-2">${title}</h1><p class="text-secondary mb-4">${subtitle}</p>${configMessage()}${form}<p class="text-secondary text-center small mt-4 mb-0">${footer}</p></div></section>`; }

export function loginPage(auth) { setDocumentMeta({ title: 'Log in — Dearly', description: 'Log in to create and manage your Dearly letters.', noIndex: true }); return renderShell(authLayout('Welcome back.', 'Your letters are waiting for you.', `<form id="login-form" novalidate><div class="mb-3"><label class="form-label" for="login-email">Email address</label><input class="form-control" id="login-email" name="email" type="email" autocomplete="email" required /></div><div class="mb-2"><label class="form-label" for="login-password">Password</label><input class="form-control" id="login-password" name="password" type="password" autocomplete="current-password" required /></div><div class="text-end mb-4"><a data-route class="small text-primary-brand" href="/forgot-password">Forgot password?</a></div>${submitButton('Log in')}</form><div class="auth-divider">or</div><button id="google-login" class="btn btn-light border w-100" type="button"><i class="bi bi-google me-2"></i>Continue with Google</button>`, `New to Dearly? <a data-route class="text-primary-brand fw-semibold" href="/register">Create an account</a>`), { path: '/login', authenticated: auth.user ? { initial: auth.initial } : false }); }

export function registerPage(auth) { setDocumentMeta({ title: 'Create an account — Dearly', description: 'Create an account and start writing memorable letters.', noIndex: true }); return renderShell(authLayout('Make it memorable.', 'Create an account to save letters, see reactions, and keep every little moment.', `<form id="register-form" novalidate><div class="mb-3"><label class="form-label" for="register-name">Your name</label><input class="form-control" id="register-name" name="displayName" autocomplete="name" maxlength="80" required /></div><div class="mb-3"><label class="form-label" for="register-email">Email address</label><input class="form-control" id="register-email" name="email" type="email" autocomplete="email" required /></div><div class="mb-4"><label class="form-label" for="register-password">Password</label><input class="form-control" id="register-password" name="password" type="password" minlength="8" autocomplete="new-password" required /><div class="form-text">Use at least 8 characters.</div></div>${submitButton('Create my account')}</form>`, `Already have an account? <a data-route class="text-primary-brand fw-semibold" href="/login">Log in</a>`), { path: '/register', authenticated: auth.user ? { initial: auth.initial } : false }); }

export function forgotPasswordPage(auth) { setDocumentMeta({ title: 'Reset password — Dearly', description: 'Reset your Dearly password.', noIndex: true }); return renderShell(authLayout('Let’s get you back in.', 'Enter your email and we’ll send a secure password reset link.', `<form id="forgot-form" novalidate><div class="mb-4"><label class="form-label" for="forgot-email">Email address</label><input class="form-control" id="forgot-email" name="email" type="email" autocomplete="email" required /></div>${submitButton('Send reset link')}</form>`, `Remembered it? <a data-route class="text-primary-brand fw-semibold" href="/login">Log in</a>`), { path: '/forgot-password', authenticated: auth.user ? { initial: auth.initial } : false }); }

export function resetPasswordPage(auth) { setDocumentMeta({ title: 'Choose a new password — Dearly', description: 'Set a new password for your Dearly account.', noIndex: true }); return renderShell(authLayout('Choose a new password.', 'Make it at least 8 characters, and keep it somewhere only you can reach.', `<form id="reset-password-form" novalidate><div class="mb-3"><label class="form-label" for="new-password">New password</label><input class="form-control" id="new-password" name="password" type="password" minlength="8" autocomplete="new-password" required /></div><div class="mb-4"><label class="form-label" for="confirm-password">Confirm new password</label><input class="form-control" id="confirm-password" name="confirmation" type="password" minlength="8" autocomplete="new-password" required /></div>${submitButton('Save new password')}</form>`, `Need a new link? <a data-route class="text-primary-brand fw-semibold" href="/forgot-password">Reset your password</a>`), { path: '/reset-password', authenticated: auth.user ? { initial: auth.initial } : false }); }

function setSubmitting(form, busy) { const button = form.querySelector('button[type="submit"]'); button.disabled = busy; button.querySelector('.spinner-border').classList.toggle('d-none', !busy); }
export function bindAuthPage(navigate) {
  document.querySelector('#login-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const email = values.get('email').trim(); if (!emailIsValid(email) || !values.get('password')) return showToast('Enter your email and password.', 'warning'); try { setSubmitting(form, true); const { error } = await requireSupabase().auth.signInWithPassword({ email, password: values.get('password') }); if (error) throw error; showToast('Welcome back.', 'success'); navigate('/dashboard'); } catch (error) { showToast(error.message, 'error', true); } finally { setSubmitting(form, false); } });
  document.querySelector('#register-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const email = values.get('email').trim(); const name = values.get('displayName').trim(); const password = values.get('password'); if (!name) return showToast('Please enter your name.', 'warning'); if (!emailIsValid(email)) return showToast('Enter a valid email address.', 'warning'); if (password.length < 8) return showToast('Choose a password with at least 8 characters.', 'warning'); try { setSubmitting(form, true); const { data, error } = await requireSupabase().auth.signUp({ email, password, options: { data: { display_name: name }, emailRedirectTo: `${location.origin}/login` } }); if (error) throw error; showToast(data.session ? 'Your account is ready.' : 'Check your inbox to confirm your email.', 'success'); navigate(data.session ? '/dashboard' : '/login'); } catch (error) { showToast(error.message, 'error', true); } finally { setSubmitting(form, false); } });
  document.querySelector('#forgot-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const email = new FormData(form).get('email').trim(); if (!emailIsValid(email)) return showToast('Enter a valid email address.', 'warning'); try { setSubmitting(form, true); const { error } = await requireSupabase().auth.resetPasswordForEmail(email, { redirectTo: `${location.origin}/reset-password` }); if (error) throw error; showToast('If that account exists, a reset link is on its way.', 'success'); } catch (error) { showToast(error.message, 'error', true); } finally { setSubmitting(form, false); } });
  document.querySelector('#reset-password-form')?.addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const password = values.get('password'); const confirmation = values.get('confirmation'); if (password.length < 8) return showToast('Choose a password with at least 8 characters.', 'warning'); if (password !== confirmation) return showToast('The passwords do not match.', 'warning'); try { setSubmitting(form, true); const { data: { session }, error: sessionError } = await requireSupabase().auth.getSession(); if (sessionError) throw sessionError; if (!session) { showToast('That reset link has expired. Request a new one to continue.', 'warning'); navigate('/forgot-password'); return; } const { error } = await requireSupabase().auth.updateUser({ password }); if (error) throw error; await requireSupabase().auth.signOut(); showToast('Your password has been updated. Please log in.', 'success'); navigate('/login'); } catch (error) { showToast(error.message, 'error', true); } finally { setSubmitting(form, false); } });
  document.querySelector('#google-login')?.addEventListener('click', async () => { try { const { error } = await requireSupabase().auth.signInWithOAuth({ provider: 'google', options: { redirectTo: `${location.origin}/dashboard` } }); if (error) throw error; } catch (error) { showToast(error.message, 'error', true); } });
}
