import { categories, templateSeeds } from '../data/templates.js';
import { renderShell } from '../components/shell.js';
import { setDocumentMeta } from '../utils/helpers.js';

function templateCard(template) {
  return `<article class="template-card"><div class="template-preview" style="--template-bg:${template.bg};--template-accent:${template.accent};--template-font:'${template.font}';"><div class="template-paper"><h3>${template.name}</h3><p>${template.body}</p></div></div><div class="template-info d-flex align-items-end justify-content-between gap-2"><div><h3>${template.name}</h3><p>${template.category}</p></div><a data-route class="btn btn-light btn-sm" href="/create-letter?template=${template.slug}">Use</a></div></article>`;
}

export function homePage(auth) {
  setDocumentMeta({ title: 'Dearly — Say what you feel, beautifully.', description: 'Create beautiful, personal digital letters to share with the people you love.' });
  const content = `<section class="hero"><div class="container"><div class="row align-items-center g-4 g-lg-5"><div class="col-lg-7"><div class="hero-copy"><span class="eyebrow">Letters, reimagined</span><h1>Say what you feel, <em>beautifully.</em></h1><p class="hero-lede">Create personal digital letters with beautiful designs, photos, music, animations, and surprises. Then share a moment they will want to keep.</p><div class="hero-actions d-sm-flex gap-3 mt-4"><a data-route href="/create-letter" class="btn btn-primary px-4">Create your letter <i class="bi bi-arrow-right ms-1"></i></a><a data-route href="/templates" class="btn btn-light px-4 mt-2 mt-sm-0">Explore templates</a></div><div class="social-proof mt-4"><div class="avatar-stack"><span style="--color:#e78e8e">M</span><span style="--color:#f0af62">J</span><span style="--color:#8fc8ba">K</span></div><span>Made for the little things worth remembering.</span></div></div></div><div class="col-lg-5"><div class="envelope-stage" aria-label="An illustrated pink envelope"><div class="hero-blob"></div><span class="floating-note note-one">for someone special</span><div class="envelope-art"><div class="envelope-back"></div><div class="envelope-paper"><div class="paper-title">A little note...</div><div class="paper-lines"><span></span><span></span><span></span></div></div><div class="envelope-front"></div><div class="envelope-flap"></div><div class="wax-seal">♥</div></div><span class="floating-note note-two">made with ♥</span></div></div></div></div></section>
  <section class="page-section"><div class="container"><div class="section-heading"><span class="eyebrow">Every kind of feeling</span><h2>There is a letter for that.</h2><p class="text-secondary mb-0">Start with a feeling. Make it entirely your own.</p></div><div class="row row-cols-2 row-cols-md-3 row-cols-lg-6 g-3">${categories.map(([name, icon, tint]) => `<div class="col"><a data-route href="/templates?category=${encodeURIComponent(name)}" class="category-card"><span class="category-icon" style="--tint:${tint}"><i class="bi bi-${icon}"></i></span><span>${name}</span></a></div>`).join('')}</div></div></section>
  <section class="page-section pt-0"><div class="container"><div class="d-flex flex-wrap align-items-end justify-content-between gap-3 mb-4"><div><span class="eyebrow">Made to be personalized</span><h2 class="display-title mb-0 mt-2">A beautiful place to begin.</h2></div><a data-route href="/templates" class="btn btn-outline-primary">View all templates <i class="bi bi-arrow-right ms-1"></i></a></div><div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">${templateSeeds.slice(0, 4).map(templateCard).join('')}</div></div></section>
  <section class="page-section" style="background:#fff2f0"><div class="container"><div class="section-heading"><span class="eyebrow">A little magic, simply made</span><h2>From your heart to theirs.</h2></div><div class="row row-cols-1 row-cols-sm-2 row-cols-lg-5 g-4">${[['1','Write','Give your thoughts a place to land.'],['2','Make it yours','Choose a design, words, photos, and details.'],['3','Wrap it up','Personalize the envelope and little surprises.'],['4','Share it','Send one private link, wherever they are.'],['5','Make their day','They open a letter, not just a page.']].map(([number,title,text]) => `<div class="col"><div class="how-step"><div class="step-number">${number}</div><h3>${title}</h3><p>${text}</p></div></div>`).join('')}</div></div></section>
  <section class="page-section"><div class="container"><div class="row align-items-center g-4"><div class="col-lg-5"><span class="eyebrow">More than a message</span><h2 class="display-title mt-2">The receiving experience is the gift.</h2><p class="text-secondary mt-3 mb-0" style="line-height:1.8">A Dearly letter arrives wrapped in an envelope. It opens with a small moment of anticipation — then makes room for every word you chose.</p></div><div class="col-lg-7"><div class="row row-cols-1 row-cols-md-3 g-3"><div class="col"><div class="feature-card"><div class="feature-icon"><i class="bi bi-palette2"></i></div><h3>Beautifully yours</h3><p>Start with a theme, then change every meaningful detail.</p></div></div><div class="col"><div class="feature-card"><div class="feature-icon" style="--icon-bg:#eaf5fb;--icon-color:#4da8da"><i class="bi bi-shield-lock"></i></div><h3>Private by design</h3><p>Share a thoughtful link without making a public post.</p></div></div><div class="col"><div class="feature-card"><div class="feature-icon" style="--icon-bg:#fff4df;--icon-color:#d89122"><i class="bi bi-stars"></i></div><h3>Small surprises</h3><p>Add memories, music, reactions, and hidden notes.</p></div></div></div></div></div></div></section>
  <section class="container pb-5"><div class="cta-panel"><span class="eyebrow" style="color:#ffaebe">Your words are worth keeping</span><h2 class="mt-2">Make someone feel remembered.</h2><p>A letter is never just a letter when it comes from you.</p><a data-route href="/create-letter" class="btn btn-primary px-4">Create your letter <i class="bi bi-arrow-right ms-1"></i></a></div></section>`;
  return renderShell(content, { authenticated: auth.user ? { initial: auth.initial } : false });
}
