import { renderShell } from '../components/shell.js';
import { requireSupabase, isSupabaseConfigured } from '../config/supabase.js';
import { escapeHtml, setDocumentMeta } from '../utils/helpers.js';
import { showToast } from '../utils/toast.js';

function profileForm(profile = {}) { return `<form id="profile-form" class="card border-0 p-3 p-md-4"><div class="d-flex align-items-center gap-3 mb-4"><div class="profile-avatar-large">${escapeHtml((profile.display_name || 'D').slice(0, 1).toUpperCase())}</div><div><h2 class="h5 mb-1">Your sender profile</h2><p class="text-secondary small mb-0">Choose what recipients can see when they open a letter.</p></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="display-name">Display name</label><input id="display-name" class="form-control" maxlength="80" value="${escapeHtml(profile.display_name || '')}" required /></div><div class="col-md-6"><label class="form-label" for="username">Username</label><input id="username" class="form-control" maxlength="30" pattern="[a-z0-9_]{3,30}" value="${escapeHtml(profile.username || '')}" placeholder="your_name" /><div class="form-text">Lowercase letters, numbers, and underscores.</div></div><div class="col-12"><label class="form-label" for="profile-bio">A little about you</label><textarea id="profile-bio" class="form-control" rows="3" maxlength="500" placeholder="Optional">${escapeHtml(profile.bio || '')}</textarea></div></div><h3 class="h6 mt-4 mb-3">Privacy and replies</h3><div class="vstack gap-3"><label class="settings-switch"><span><strong>Allow anonymous letters</strong><small>Let people send you a letter without signing in.</small></span><input id="allow-anonymous" class="form-check-input" type="checkbox" ${profile.allow_anonymous_letters !== false ? 'checked' : ''} /></label><label class="settings-switch"><span><strong>Allow replies</strong><small>Let recipients write back from a letter you send.</small></span><input id="allow-replies" class="form-check-input" type="checkbox" ${profile.allow_replies !== false ? 'checked' : ''} /></label><label class="settings-switch"><span><strong>Allow reactions</strong><small>Let recipients leave a small reaction.</small></span><input id="allow-reactions" class="form-check-input" type="checkbox" ${profile.allow_reactions !== false ? 'checked' : ''} /></label></div><div class="d-flex justify-content-end mt-4"><button class="btn btn-primary" type="submit">Save changes</button></div></form>`; }

export function profilePage(auth) { setDocumentMeta({ title: 'Profile — Dearly', description: 'Manage your Dearly profile and preferences.', noIndex: true }); return renderShell(`<section class="container app-page"><header class="app-header"><span class="eyebrow">Your little corner</span><h1>Profile and settings</h1><p class="mb-0">Control how your letters feel and who can connect with you.</p></header><div id="profile-content"><div class="card border-0 p-4"><div class="loading-skeleton" style="height:330px"></div></div></div></section>`, { path: '/profile', authenticated: { initial: auth.initial } }); }

export async function loadProfile(auth) { const target = document.querySelector('#profile-content'); if (!isSupabaseConfigured) { target.innerHTML = profileForm({ display_name: auth.user.user_metadata?.display_name || '' }); return; } try { const { data, error } = await requireSupabase().from('profiles').select('*').eq('id', auth.user.id).single(); if (error) throw error; target.innerHTML = profileForm(data); } catch (error) { target.innerHTML = `<div class="empty-state card"><div class="empty-state-icon">☁️</div><h2 class="h4">Your profile couldn’t load.</h2><p class="text-secondary">${escapeHtml(error.message)}</p></div>`; } }

export function bindProfile(auth) { document.addEventListener('submit', async (event) => { if (event.target.id !== 'profile-form') return; event.preventDefault(); const displayName = document.querySelector('#display-name').value.trim(); const username = document.querySelector('#username').value.trim(); if (!displayName) return showToast('Add a display name.', 'warning'); if (username && !/^[a-z0-9_]{3,30}$/.test(username)) return showToast('Use 3–30 lowercase letters, numbers, or underscores for your username.', 'warning'); try { const { error } = await requireSupabase().from('profiles').update({ display_name: displayName, username: username || null, bio: document.querySelector('#profile-bio').value.trim() || null, allow_anonymous_letters: document.querySelector('#allow-anonymous').checked, allow_replies: document.querySelector('#allow-replies').checked, allow_reactions: document.querySelector('#allow-reactions').checked }).eq('id', auth.user.id); if (error) throw error; showToast('Profile saved.', 'success'); } catch (error) { showToast(error.message, 'error', true); } }); }
