import { isSupabaseConfigured } from '../config/supabase.js';
import { categoryPresentation, fetchPublishedTemplates, fetchTemplateCategories } from '../data/template-catalogue.js';
import { renderShell } from '../components/shell.js';
import { escapeHtml, setDocumentMeta } from '../utils/helpers.js';

let currentTemplates = [];

function card(template) { return `<article class="template-card h-100"><div class="template-preview" style="--template-bg:${template.bg};--template-accent:${template.accent};--template-font:'${template.font}';"><div class="template-paper"><h3>${escapeHtml(template.name)}</h3><p>${escapeHtml(template.body)}</p></div></div><div class="template-info"><div class="d-flex justify-content-between gap-2"><div><span class="eyebrow" style="font-size:.62rem">${escapeHtml(template.category)}</span><h3>${escapeHtml(template.name)}</h3></div><button class="btn btn-light btn-sm template-preview-btn" data-template="${escapeHtml(template.slug)}"><i class="bi bi-eye"></i><span class="visually-hidden">Preview ${escapeHtml(template.name)}</span></button></div><p>${escapeHtml(template.description)}</p><a data-route class="btn btn-primary btn-sm mt-2" href="/create-letter?template=${encodeURIComponent(template.slug)}">Use this template</a></div></article>`; }
function emptyMarkup(icon = '💌', title = 'No templates here yet', text = 'Try another category, or create something from scratch.') { return `<div class="col-12"><div class="empty-state card"><div class="empty-state-icon">${icon}</div><h2 class="h4">${title}</h2><p class="text-secondary">${text}</p><a data-route class="btn btn-primary" href="/create-letter">Create a blank letter</a></div></div>`; }
function renderTemplates(items) { const grid = document.querySelector('#template-grid'); if (grid) grid.innerHTML = items.length ? items.map((template) => `<div class="col">${card(template)}</div>`).join('') : emptyMarkup(); }
function categoryLinks(categories, selected) { return `<a data-route href="/templates" class="btn btn-sm ${selected === 'All' ? 'btn-primary' : 'btn-light'}">All</a>${categories.map((category) => `<a data-route href="/templates?category=${encodeURIComponent(category.name)}" class="btn btn-sm ${selected === category.name ? 'btn-primary' : 'btn-light'}">${escapeHtml(category.name)}</a>`).join('')}`; }

export function templatesPage(auth) {
  setDocumentMeta({ title: 'Letter templates — Dearly', description: 'Start your letter with a beautiful, customizable Dearly template.' });
  const content = `<section class="container app-page"><header class="app-header text-center"><span class="eyebrow">A beautiful first draft</span><h1>Find a feeling. Make it yours.</h1><p class="mb-0">Every template is a starting point — your words make it personal.</p></header><div class="row justify-content-center mb-4"><div class="col-lg-6"><label class="visually-hidden" for="template-search">Search templates</label><div class="input-group"><span class="input-group-text bg-white border-end-0"><i class="bi bi-search"></i></span><input id="template-search" class="form-control border-start-0" type="search" placeholder="Search by mood, occasion, or style" /></div></div></div><div id="template-category-filters" class="d-flex flex-wrap justify-content-center gap-2 mb-5" aria-label="Template categories"></div><div id="template-grid" class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-4"><div class="col-12"><div class="p-4"><div class="loading-skeleton" style="height:250px"></div></div></div></div></section><div class="modal fade" id="template-modal" tabindex="-1" aria-labelledby="template-modal-title" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0"><div class="modal-header border-0"><h2 class="modal-title h5" id="template-modal-title">Template preview</h2><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body pt-0" id="template-modal-content"></div></div></div></div>`;
  return renderShell(content, { path: '/templates', authenticated: auth.user ? { initial: auth.initial } : false });
}

export function bindTemplatePage() {
  const input = document.querySelector('#template-search'); const grid = document.querySelector('#template-grid');
  input?.addEventListener('input', () => { const query = input.value.toLowerCase().trim(); renderTemplates(currentTemplates.filter((item) => `${item.name} ${item.category} ${item.description}`.toLowerCase().includes(query))); });
  grid?.addEventListener('click', (event) => { const button = event.target.closest('.template-preview-btn'); if (!button) return; const item = currentTemplates.find((template) => template.slug === button.dataset.template); if (!item) return; const target = document.querySelector('#template-modal-content'); target.innerHTML = `<div class="template-preview rounded-3" style="--template-bg:${item.bg};--template-accent:${item.accent};--template-font:'${item.font}'"><div class="template-paper"><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.body)}</p></div></div><p class="text-secondary mt-3 mb-0">${escapeHtml(item.description)}</p><a data-route data-bs-dismiss="modal" href="/create-letter?template=${encodeURIComponent(item.slug)}" class="btn btn-primary w-100 mt-3">Use this template</a>`; window.bootstrap.Modal.getOrCreateInstance(document.querySelector('#template-modal')).show(); });
}

export async function loadTemplates() {
  const grid = document.querySelector('#template-grid'); const filters = document.querySelector('#template-category-filters'); const selected = new URLSearchParams(location.search).get('category') || 'All';
  if (!isSupabaseConfigured) { if (filters) filters.innerHTML = ''; if (grid) grid.innerHTML = emptyMarkup('🔌', 'Connect your template catalogue', 'Add your Supabase settings to load the live template collection.'); return; }
  try { const [templates, categories] = await Promise.all([fetchPublishedTemplates(), fetchTemplateCategories()]); currentTemplates = templates; const visibleCategories = categories.length ? categories : [...new Map(templates.map((item) => [item.category, categoryPresentation({ name: item.category, slug: item.category.toLowerCase() })])).values()]; if (filters) filters.innerHTML = categoryLinks(visibleCategories, selected); renderTemplates(selected === 'All' ? templates : templates.filter((item) => item.category === selected)); } catch (error) { if (filters) filters.innerHTML = ''; if (grid) grid.innerHTML = emptyMarkup('☁️', 'Templates couldn’t load', escapeHtml(error.message)); }
}
